git rm --cached .gradle/5.6.4/executionHistory/executionHistory.bin
git rm --cached .gradle/5.6.4/executionHistory/executionHistory.lock
git rm --cached .gradle/5.6.4/fileChanges/last-build.bin
git rm --cached .gradle/5.6.4/fileContent/fileContent.lock
git rm --cached .gradle/5.6.4/fileHashes/fileHashes.bin
git rm --cached .gradle/5.6.4/fileHashes/fileHashes.lock
git rm --cached .gradle/5.6.4/fileHashes/resourceHashesCache.bin
git rm --cached .gradle/5.6.4/gc.properties
git rm --cached .gradle/5.6.4/javaCompile/classAnalysis.bin
git rm --cached .gradle/5.6.4/javaCompile/jarAnalysis.bin
git rm --cached .gradle/5.6.4/javaCompile/javaCompile.lock
git rm --cached .gradle/5.6.4/javaCompile/taskHistory.bin
git rm --cached .gradle/buildOutputCleanup/buildOutputCleanup.lock
git rm --cached .gradle/buildOutputCleanup/cache.properties
git rm --cached .gradle/buildOutputCleanup/outputFiles.bin
git rm --cached .gradle/vcs-1/gc.properties
git rm --cached .idea/caches/build_file_checksums.ser
git rm --cached .idea/caches/gradle_models.ser
git rm --cached .idea/libraries/Gradle____local_aars___C__Desarrollo_workspaces_wks_and_FRMDRD_app_libs_groovy_android_2_4_16_jar_unspecified_jar.xml
git rm --cached .idea/libraries/Gradle__androidx_activity_activity_1_0_0_aar.xml
git rm --cached .idea/libraries/Gradle__androidx_annotation_annotation_1_1_0_jar.xml
git rm --cached .idea/libraries/Gradle__androidx_appcompat_appcompat_1_1_0_aar.xml
git rm --cached .idea/libraries/Gradle__androidx_appcompat_appcompat_resources_1_1_0_aar.xml
git rm --cached .idea/libraries/Gradle__androidx_arch_core_core_common_2_1_0_jar.xml
git rm --cached .idea/libraries/Gradle__androidx_arch_core_core_runtime_2_0_0_aar.xml
git rm --cached .idea/libraries/Gradle__androidx_asynclayoutinflater_asynclayoutinflater_1_0_0_aar.xml
git rm --cached .idea/libraries/Gradle__androidx_cardview_cardview_1_0_0_aar.xml
git rm --cached .idea/libraries/Gradle__androidx_collection_collection_1_1_0_jar.xml
git rm --cached .idea/libraries/Gradle__androidx_constraintlayout_constraintlayout_1_1_3_aar.xml
git rm --cached .idea/libraries/Gradle__androidx_constraintlayout_constraintlayout_solver_1_1_3_jar.xml
git rm --cached .idea/libraries/Gradle__androidx_coordinatorlayout_coordinatorlayout_1_0_0_aar.xml
git rm --cached .idea/libraries/Gradle__androidx_core_core_1_1_0_aar.xml
git rm --cached .idea/libraries/Gradle__androidx_cursoradapter_cursoradapter_1_0_0_aar.xml
git rm --cached .idea/libraries/Gradle__androidx_customview_customview_1_0_0_aar.xml
git rm --cached .idea/libraries/Gradle__androidx_databinding_databinding_adapters_3_6_0_aar.xml
git rm --cached .idea/libraries/Gradle__androidx_databinding_databinding_common_3_6_0_jar.xml
git rm --cached .idea/libraries/Gradle__androidx_databinding_databinding_runtime_3_6_0_aar.xml
git rm --cached .idea/libraries/Gradle__androidx_databinding_viewbinding_3_6_0_aar.xml
git rm --cached .idea/libraries/Gradle__androidx_documentfile_documentfile_1_0_0_aar.xml
git rm --cached .idea/libraries/Gradle__androidx_drawerlayout_drawerlayout_1_0_0_aar.xml
git rm --cached .idea/libraries/Gradle__androidx_fragment_fragment_1_1_0_aar.xml
git rm --cached .idea/libraries/Gradle__androidx_interpolator_interpolator_1_0_0_aar.xml
git rm --cached .idea/libraries/Gradle__androidx_legacy_legacy_support_core_ui_1_0_0_aar.xml
git rm --cached .idea/libraries/Gradle__androidx_legacy_legacy_support_core_utils_1_0_0_aar.xml
git rm --cached .idea/libraries/Gradle__androidx_lifecycle_lifecycle_common_2_1_0_jar.xml
git rm --cached .idea/libraries/Gradle__androidx_lifecycle_lifecycle_livedata_2_0_0_aar.xml
git rm --cached .idea/libraries/Gradle__androidx_lifecycle_lifecycle_livedata_core_2_0_0_aar.xml
git rm --cached .idea/libraries/Gradle__androidx_lifecycle_lifecycle_runtime_2_1_0_aar.xml
git rm --cached .idea/libraries/Gradle__androidx_lifecycle_lifecycle_viewmodel_2_1_0_aar.xml
git rm --cached .idea/libraries/Gradle__androidx_loader_loader_1_0_0_aar.xml
git rm --cached .idea/libraries/Gradle__androidx_localbroadcastmanager_localbroadcastmanager_1_0_0_aar.xml
git rm --cached .idea/libraries/Gradle__androidx_print_print_1_0_0_aar.xml
git rm --cached .idea/libraries/Gradle__androidx_recyclerview_recyclerview_1_0_0_aar.xml
git rm --cached .idea/libraries/Gradle__androidx_savedstate_savedstate_1_0_0_aar.xml
git rm --cached .idea/libraries/Gradle__androidx_slidingpanelayout_slidingpanelayout_1_0_0_aar.xml
git rm --cached .idea/libraries/Gradle__androidx_swiperefreshlayout_swiperefreshlayout_1_0_0_aar.xml
git rm --cached .idea/libraries/Gradle__androidx_transition_transition_1_0_0_aar.xml
git rm --cached .idea/libraries/Gradle__androidx_vectordrawable_vectordrawable_1_1_0_aar.xml
git rm --cached .idea/libraries/Gradle__androidx_vectordrawable_vectordrawable_animated_1_1_0_aar.xml
git rm --cached .idea/libraries/Gradle__androidx_versionedparcelable_versionedparcelable_1_1_0_aar.xml
git rm --cached .idea/libraries/Gradle__androidx_viewpager_viewpager_1_0_0_aar.xml
git rm --cached .idea/libraries/Gradle__com_google_android_material_material_1_0_0_aar.xml
git rm --cached .idea/libraries/Gradle__com_google_android_tools_dx_1_7_jar.xml
git rm --cached .idea/libraries/Gradle__com_google_dagger_dagger_2_26_jar.xml
git rm --cached .idea/libraries/Gradle__com_thoughtworks_xstream_xstream_1_3_1_jar.xml
git rm --cached .idea/libraries/Gradle__com_vividsolutions_jts_core_1_14_0_jar.xml
git rm --cached .idea/libraries/Gradle__commons_collections_commons_collections_20040616_jar.xml
git rm --cached .idea/libraries/Gradle__commons_lang_commons_lang_20030203_000129_jar.xml
git rm --cached .idea/libraries/Gradle__commons_logging_commons_logging_1_2_jar.xml
git rm --cached .idea/libraries/Gradle__es_jcyl_ita_crtcyl_crtcyl_core_2_37_0_jar.xml
git rm --cached .idea/libraries/Gradle__es_jcyl_ita_crtrepo_repo_0_1_0_SNAPSHOT_jar.xml
git rm --cached .idea/libraries/Gradle__javax_inject_javax_inject_1_jar.xml
git rm --cached .idea/libraries/Gradle__org_apache_commons_commons_jexl3_3_1_jar.xml
git rm --cached .idea/libraries/Gradle__org_greenrobot_greendao_3_2_3_patched_SNAPSHOT_jar.xml
git rm --cached .idea/libraries/Gradle__org_greenrobot_greendao_api_3_2_3_patched_SNAPSHOT_jar.xml
git rm --cached .idea/libraries/Gradle__xpp3_xpp3_1_1_4c_jar.xml
git rm --cached .idea/modules.xml
git rm --cached FormuDruid.iml
git rm --cached app/app.iml
git rm --cached app/build/generated/ap_generated_sources/debug/out/androidx/databinding/DataBinderMapperImpl.java
git rm --cached app/build/generated/ap_generated_sources/debug/out/androidx/databinding/DataBindingComponent.java
git rm --cached app/build/generated/ap_generated_sources/debug/out/androidx/databinding/library/baseAdapters/BR.java
git rm --cached app/build/generated/ap_generated_sources/debug/out/es/jcyl/ita/frmdrd/BR.java
git rm --cached app/build/generated/ap_generated_sources/debug/out/es/jcyl/ita/frmdrd/DataBinderMapperImpl.java
git rm --cached app/build/generated/source/buildConfig/debug/es/jcyl/ita/frmdrd/BuildConfig.java
git rm --cached app/build/generated/source/dataBinding/trigger/debug/es/jcyl/ita/frmdrd/DataBindingInfo.java
git rm --cached app/build/intermediates/annotation_processor_list/debug/annotationProcessors.json
git rm --cached app/build/intermediates/apk_list/debug/apk-list.gson
git rm --cached app/build/intermediates/blame/res/debug/multi-v2/debug.json
git rm --cached app/build/intermediates/blame/res/debug/multi-v2/values-af.json
git rm --cached app/build/intermediates/blame/res/debug/multi-v2/values-am.json
git rm --cached app/build/intermediates/blame/res/debug/multi-v2/values-ar.json
git rm --cached app/build/intermediates/blame/res/debug/multi-v2/values-as.json
git rm --cached app/build/intermediates/blame/res/debug/multi-v2/values-az.json
git rm --cached app/build/intermediates/blame/res/debug/multi-v2/values-b+sr+Latn.json
git rm --cached app/build/intermediates/blame/res/debug/multi-v2/values-be.json
git rm --cached app/build/intermediates/blame/res/debug/multi-v2/values-bg.json
git rm --cached app/build/intermediates/blame/res/debug/multi-v2/values-bn.json
git rm --cached app/build/intermediates/blame/res/debug/multi-v2/values-bs.json
git rm --cached app/build/intermediates/blame/res/debug/multi-v2/values-ca.json
git rm --cached app/build/intermediates/blame/res/debug/multi-v2/values-cs.json
git rm --cached app/build/intermediates/blame/res/debug/multi-v2/values-da.json
git rm --cached app/build/intermediates/blame/res/debug/multi-v2/values-de.json
git rm --cached app/build/intermediates/blame/res/debug/multi-v2/values-el.json
git rm --cached app/build/intermediates/blame/res/debug/multi-v2/values-en-rAU.json
git rm --cached app/build/intermediates/blame/res/debug/multi-v2/values-en-rCA.json
git rm --cached app/build/intermediates/blame/res/debug/multi-v2/values-en-rGB.json
git rm --cached app/build/intermediates/blame/res/debug/multi-v2/values-en-rIN.json
git rm --cached app/build/intermediates/blame/res/debug/multi-v2/values-en-rXC.json
git rm --cached app/build/intermediates/blame/res/debug/multi-v2/values-es-rUS.json
git rm --cached app/build/intermediates/blame/res/debug/multi-v2/values-es.json
git rm --cached app/build/intermediates/blame/res/debug/multi-v2/values-et.json
git rm --cached app/build/intermediates/blame/res/debug/multi-v2/values-eu.json
git rm --cached app/build/intermediates/blame/res/debug/multi-v2/values-fa.json
git rm --cached app/build/intermediates/blame/res/debug/multi-v2/values-fi.json
git rm --cached app/build/intermediates/blame/res/debug/multi-v2/values-fr-rCA.json
git rm --cached app/build/intermediates/blame/res/debug/multi-v2/values-fr.json
git rm --cached app/build/intermediates/blame/res/debug/multi-v2/values-gl.json
git rm --cached app/build/intermediates/blame/res/debug/multi-v2/values-gu.json
git rm --cached app/build/intermediates/blame/res/debug/multi-v2/values-h720dp-v13.json
git rm --cached app/build/intermediates/blame/res/debug/multi-v2/values-hdpi-v4.json
git rm --cached app/build/intermediates/blame/res/debug/multi-v2/values-hi.json
git rm --cached app/build/intermediates/blame/res/debug/multi-v2/values-hr.json
git rm --cached app/build/intermediates/blame/res/debug/multi-v2/values-hu.json
git rm --cached app/build/intermediates/blame/res/debug/multi-v2/values-hy.json
git rm --cached app/build/intermediates/blame/res/debug/multi-v2/values-in.json
git rm --cached app/build/intermediates/blame/res/debug/multi-v2/values-is.json
git rm --cached app/build/intermediates/blame/res/debug/multi-v2/values-it.json
git rm --cached app/build/intermediates/blame/res/debug/multi-v2/values-iw.json
git rm --cached app/build/intermediates/blame/res/debug/multi-v2/values-ja.json
git rm --cached app/build/intermediates/blame/res/debug/multi-v2/values-ka.json
git rm --cached app/build/intermediates/blame/res/debug/multi-v2/values-kk.json
git rm --cached app/build/intermediates/blame/res/debug/multi-v2/values-km.json
git rm --cached app/build/intermediates/blame/res/debug/multi-v2/values-kn.json
git rm --cached app/build/intermediates/blame/res/debug/multi-v2/values-ko.json
git rm --cached app/build/intermediates/blame/res/debug/multi-v2/values-ky.json
git rm --cached app/build/intermediates/blame/res/debug/multi-v2/values-land.json
git rm --cached app/build/intermediates/blame/res/debug/multi-v2/values-large-v4.json
git rm --cached app/build/intermediates/blame/res/debug/multi-v2/values-ldltr-v21.json
git rm --cached app/build/intermediates/blame/res/debug/multi-v2/values-lo.json
git rm --cached app/build/intermediates/blame/res/debug/multi-v2/values-lt.json
git rm --cached app/build/intermediates/blame/res/debug/multi-v2/values-lv.json
git rm --cached app/build/intermediates/blame/res/debug/multi-v2/values-mk.json
git rm --cached app/build/intermediates/blame/res/debug/multi-v2/values-ml.json
git rm --cached app/build/intermediates/blame/res/debug/multi-v2/values-mn.json
git rm --cached app/build/intermediates/blame/res/debug/multi-v2/values-mr.json
git rm --cached app/build/intermediates/blame/res/debug/multi-v2/values-ms.json
git rm --cached app/build/intermediates/blame/res/debug/multi-v2/values-my.json
git rm --cached app/build/intermediates/blame/res/debug/multi-v2/values-nb.json
git rm --cached app/build/intermediates/blame/res/debug/multi-v2/values-ne.json
git rm --cached app/build/intermediates/blame/res/debug/multi-v2/values-night-v8.json
git rm --cached app/build/intermediates/blame/res/debug/multi-v2/values-nl.json
git rm --cached app/build/intermediates/blame/res/debug/multi-v2/values-or.json
git rm --cached app/build/intermediates/blame/res/debug/multi-v2/values-pa.json
git rm --cached app/build/intermediates/blame/res/debug/multi-v2/values-pl.json
git rm --cached app/build/intermediates/blame/res/debug/multi-v2/values-port.json
git rm --cached app/build/intermediates/blame/res/debug/multi-v2/values-pt-rBR.json
git rm --cached app/build/intermediates/blame/res/debug/multi-v2/values-pt-rPT.json
git rm --cached app/build/intermediates/blame/res/debug/multi-v2/values-pt.json
git rm --cached app/build/intermediates/blame/res/debug/multi-v2/values-ro.json
git rm --cached app/build/intermediates/blame/res/debug/multi-v2/values-ru.json
git rm --cached app/build/intermediates/blame/res/debug/multi-v2/values-si.json
git rm --cached app/build/intermediates/blame/res/debug/multi-v2/values-sk.json
git rm --cached app/build/intermediates/blame/res/debug/multi-v2/values-sl.json
git rm --cached app/build/intermediates/blame/res/debug/multi-v2/values-sq.json
git rm --cached app/build/intermediates/blame/res/debug/multi-v2/values-sr.json
git rm --cached app/build/intermediates/blame/res/debug/multi-v2/values-sv.json
git rm --cached app/build/intermediates/blame/res/debug/multi-v2/values-sw.json
git rm --cached app/build/intermediates/blame/res/debug/multi-v2/values-sw600dp-v13.json
git rm --cached app/build/intermediates/blame/res/debug/multi-v2/values-ta.json
git rm --cached app/build/intermediates/blame/res/debug/multi-v2/values-te.json
git rm --cached app/build/intermediates/blame/res/debug/multi-v2/values-th.json
git rm --cached app/build/intermediates/blame/res/debug/multi-v2/values-tl.json
git rm --cached app/build/intermediates/blame/res/debug/multi-v2/values-tr.json
git rm --cached app/build/intermediates/blame/res/debug/multi-v2/values-uk.json
git rm --cached app/build/intermediates/blame/res/debug/multi-v2/values-ur.json
git rm --cached app/build/intermediates/blame/res/debug/multi-v2/values-uz.json
git rm --cached app/build/intermediates/blame/res/debug/multi-v2/values-v16.json
git rm --cached app/build/intermediates/blame/res/debug/multi-v2/values-v17.json
git rm --cached app/build/intermediates/blame/res/debug/multi-v2/values-v18.json
git rm --cached app/build/intermediates/blame/res/debug/multi-v2/values-v21.json
git rm --cached app/build/intermediates/blame/res/debug/multi-v2/values-v22.json
git rm --cached app/build/intermediates/blame/res/debug/multi-v2/values-v23.json
git rm --cached app/build/intermediates/blame/res/debug/multi-v2/values-v24.json
git rm --cached app/build/intermediates/blame/res/debug/multi-v2/values-v25.json
git rm --cached app/build/intermediates/blame/res/debug/multi-v2/values-v26.json
git rm --cached app/build/intermediates/blame/res/debug/multi-v2/values-v28.json
git rm --cached app/build/intermediates/blame/res/debug/multi-v2/values-vi.json
git rm --cached app/build/intermediates/blame/res/debug/multi-v2/values-watch-v20.json
git rm --cached app/build/intermediates/blame/res/debug/multi-v2/values-watch-v21.json
git rm --cached app/build/intermediates/blame/res/debug/multi-v2/values-xlarge-v4.json
git rm --cached app/build/intermediates/blame/res/debug/multi-v2/values-zh-rCN.json
git rm --cached app/build/intermediates/blame/res/debug/multi-v2/values-zh-rHK.json
git rm --cached app/build/intermediates/blame/res/debug/multi-v2/values-zh-rTW.json
git rm --cached app/build/intermediates/blame/res/debug/multi-v2/values-zu.json
git rm --cached app/build/intermediates/blame/res/debug/multi-v2/values.json
git rm --cached app/build/intermediates/blame/res/debug/single/debug.json
git rm --cached app/build/intermediates/bundle_manifest/debug/bundle-manifest/AndroidManifest.xml
git rm --cached app/build/intermediates/bundle_manifest/debug/bundle-manifest/output.json
git rm --cached app/build/intermediates/compatible_screen_manifest/debug/out/output.json
git rm --cached app/build/intermediates/compile_and_runtime_not_namespaced_r_class_jar/debug/R.jar
git rm --cached app/build/intermediates/data_binding_artifact/debug/out/es.jcyl.ita.frmdrd-br.bin
git rm --cached app/build/intermediates/data_binding_artifact/debug/out/es.jcyl.ita.frmdrd-setter_store.json
git rm --cached app/build/intermediates/data_binding_base_class_log_artifact/debug/out/es.jcyl.ita.frmdrd-binding_classes.json
git rm --cached app/build/intermediates/data_binding_base_class_logs_dependency_artifacts/debug/out/androidx.databinding.library.baseAdapters-binding_classes.json
git rm --cached app/build/intermediates/data_binding_dependency_artifacts/debug/out/androidx.databinding.library.baseAdapters-br.bin
git rm --cached app/build/intermediates/data_binding_dependency_artifacts/debug/out/androidx.databinding.library.baseAdapters-setter_store.json
git rm --cached app/build/intermediates/dex/debug/mergeExtDexDebug/out/classes.dex
git rm --cached app/build/intermediates/dex/debug/mergeExtDexDebug/out/classes2.dex
git rm --cached app/build/intermediates/dex/debug/mergeProjectDexDebug/out/classes.dex
git rm --cached app/build/intermediates/dex_archive_input_jar_hashes/debug/out
git rm --cached app/build/intermediates/external_file_lib_dex_archives/debug/out/0_jetified-groovy-android-2.4.16.jar
git rm --cached app/build/intermediates/feature_data_binding_base_feature_info/debug/out/all_features.json
git rm --cached app/build/intermediates/incremental/dataBindingGenBaseClassesDebug/base_builder_log.json
git rm --cached app/build/intermediates/incremental/debug-mergeJavaRes/merge-state
git rm --cached app/build/intermediates/incremental/debug-mergeJavaRes/zip-cache/+Ct8x92_FWMsl2cfd7zkJFO3ZnQ=
git rm --cached app/build/intermediates/incremental/debug-mergeJavaRes/zip-cache/+Eacf_SMdc7wXY+Xsaxvd0uEbkY=
git rm --cached app/build/intermediates/incremental/debug-mergeJavaRes/zip-cache/02hzMNvGwIg2khdp2j4HnwS4wsE=
git rm --cached app/build/intermediates/incremental/debug-mergeJavaRes/zip-cache/11_TK9_+DQd450hTe9K6twozdaI=
git rm --cached app/build/intermediates/incremental/debug-mergeJavaRes/zip-cache/3eLpKFkt3JHLz8qaR3q9SFOCMJE=
git rm --cached app/build/intermediates/incremental/debug-mergeJavaRes/zip-cache/3lkrxYON+icVv_G_Ry_ORS_r6lA=
git rm --cached app/build/intermediates/incremental/debug-mergeJavaRes/zip-cache/3r_4A45birVST30Dc4jPw0QQTpE=
git rm --cached app/build/intermediates/incremental/debug-mergeJavaRes/zip-cache/4tMdGY654UXRy_bmoZ4EWzGBOWE=
git rm --cached app/build/intermediates/incremental/debug-mergeJavaRes/zip-cache/53CP9zBX4I8YqCcMTs22QTz4hcM=
git rm --cached app/build/intermediates/incremental/debug-mergeJavaRes/zip-cache/72kDQhw5ALyRBWX5KbrJyjT0Ckc=
git rm --cached app/build/intermediates/incremental/debug-mergeJavaRes/zip-cache/8FmYRrruUSbHYlx2ZHk_oLH8mdM=
git rm --cached app/build/intermediates/incremental/debug-mergeJavaRes/zip-cache/BguPHJCvbI6yfLWll_q2KFGAydY=
git rm --cached app/build/intermediates/incremental/debug-mergeJavaRes/zip-cache/BlevbGaYumtuA1d5IxDknml1q5w=
git rm --cached app/build/intermediates/incremental/debug-mergeJavaRes/zip-cache/CG5L6oBY3aOAOEh2cKZQp+bpdcw=
git rm --cached app/build/intermediates/incremental/debug-mergeJavaRes/zip-cache/E+yj20u2eCRTtUpttqAUVEBeO1U=
git rm --cached app/build/intermediates/incremental/debug-mergeJavaRes/zip-cache/E4w4ebdUrjjkMtapZaAAqXOSgrs=
git rm --cached app/build/intermediates/incremental/debug-mergeJavaRes/zip-cache/FobRWm5yrxJd+wdFQmOTCS67eAM=
git rm --cached app/build/intermediates/incremental/debug-mergeJavaRes/zip-cache/G1pjCdxWKH0AHkj7pQPxmXO52aU=
git rm --cached app/build/intermediates/incremental/debug-mergeJavaRes/zip-cache/GXpO2MgSyl_WvoqBZZNEUUGl0kM=
git rm --cached app/build/intermediates/incremental/debug-mergeJavaRes/zip-cache/GocoNuSivdZz6VKqQHINhRfJ2jw=
git rm --cached app/build/intermediates/incremental/debug-mergeJavaRes/zip-cache/KoK_crDqg1XEtzccdZe9wXXWyFk=
git rm --cached app/build/intermediates/incremental/debug-mergeJavaRes/zip-cache/KohrFwl0fc5fy717cYBN9CtLJdY=
git rm --cached app/build/intermediates/incremental/debug-mergeJavaRes/zip-cache/LWQ_rNI31EJO2xEUzedPphrELd4=
git rm --cached app/build/intermediates/incremental/debug-mergeJavaRes/zip-cache/LjXElCWSy5vSIUosc3q8A3FJbz0=
git rm --cached app/build/intermediates/incremental/debug-mergeJavaRes/zip-cache/LxWBpRRDMB9UoQWFoHuL1u4KPIc=
git rm --cached app/build/intermediates/incremental/debug-mergeJavaRes/zip-cache/Mwi3n6dZxsaDpRApF8d1tKpRmkI=
git rm --cached app/build/intermediates/incremental/debug-mergeJavaRes/zip-cache/QYUflg+nm5lBlWWLNbtYOZK76Fc=
git rm --cached app/build/intermediates/incremental/debug-mergeJavaRes/zip-cache/T1fIZMNkOkDJN75RbCpeVZhTyaU=
git rm --cached app/build/intermediates/incremental/debug-mergeJavaRes/zip-cache/T3SAKDf5q_UH8FFstEa05jjDCFo=
git rm --cached app/build/intermediates/incremental/debug-mergeJavaRes/zip-cache/T7vFtfjIFKJz3p9JzlihgML6v44=
git rm --cached app/build/intermediates/incremental/debug-mergeJavaRes/zip-cache/THQuE5JAiihtSsk1YARAXNcHr1I=
git rm --cached app/build/intermediates/incremental/debug-mergeJavaRes/zip-cache/U1wMWIw7m8eL+CAYyhYvwEvLZ8I=
git rm --cached app/build/intermediates/incremental/debug-mergeJavaRes/zip-cache/U8_yeXlEasBo1cCQYwZ9cFuNQeU=
git rm --cached app/build/intermediates/incremental/debug-mergeJavaRes/zip-cache/W7zv41GAVSykiF8sdLqilbtQnoE=
git rm --cached app/build/intermediates/incremental/debug-mergeJavaRes/zip-cache/WDAFa2xQl+oUFlinv8oVRlxGLmY=
git rm --cached app/build/intermediates/incremental/debug-mergeJavaRes/zip-cache/X8LGyxdRJAeDKRK2RfnrRloR9_o=
git rm --cached app/build/intermediates/incremental/debug-mergeJavaRes/zip-cache/Xsel8euWibo5wzmgEaWRAbcCOgs=
git rm --cached app/build/intermediates/incremental/debug-mergeJavaRes/zip-cache/YFgw_HPNYwXsbgcg35ENRNXjcek=
git rm --cached app/build/intermediates/incremental/debug-mergeJavaRes/zip-cache/ZQdg31S65uUrR9Rj5eJzryhWtgI=
git rm --cached app/build/intermediates/incremental/debug-mergeJavaRes/zip-cache/_3J0lGdHoz41Sj2rqtRV8_wlwU0=
git rm --cached app/build/intermediates/incremental/debug-mergeJavaRes/zip-cache/_4QpE8KKtu3tWVnKFUYmvVIkxV4=
git rm --cached app/build/intermediates/incremental/debug-mergeJavaRes/zip-cache/_5VM2ZIT1GO8Q2U5lsJe8tqHkAM=
git rm --cached app/build/intermediates/incremental/debug-mergeJavaRes/zip-cache/aK_NEcr2foDmc9Bi_uxpCc6rH0o=
git rm --cached app/build/intermediates/incremental/debug-mergeJavaRes/zip-cache/avL2NrFgeG9oVy34xMxDvnZstXk=
git rm --cached app/build/intermediates/incremental/debug-mergeJavaRes/zip-cache/cbWZeUhgcFoz6pWg_tCvFQ4mH0g=
git rm --cached app/build/intermediates/incremental/debug-mergeJavaRes/zip-cache/dk03fbRkqzDWJb7U05muUdm3oWA=
git rm --cached app/build/intermediates/incremental/debug-mergeJavaRes/zip-cache/elmtLe8O8YoeqmgQ+56Qna3zhjk=
git rm --cached app/build/intermediates/incremental/debug-mergeJavaRes/zip-cache/i5oD1AreodMXyUAnk8xW49QqY8U=
git rm --cached app/build/intermediates/incremental/debug-mergeJavaRes/zip-cache/m6aQboSqOdlFKxO7kMb2CFaDlSQ=
git rm --cached app/build/intermediates/incremental/debug-mergeJavaRes/zip-cache/nczDUoIrtAM6EPBwCnsG7_ipb48=
git rm --cached app/build/intermediates/incremental/debug-mergeJavaRes/zip-cache/o1U7+Mh45iCVb+Kpx0tB0IJSIDU=
git rm --cached app/build/intermediates/incremental/debug-mergeJavaRes/zip-cache/ocO94zrF+F6whrUpkUCPk8Z6UFs=
git rm --cached app/build/intermediates/incremental/debug-mergeJavaRes/zip-cache/peXu2uAflMypeqU60NnuUEumSz4=
git rm --cached app/build/intermediates/incremental/debug-mergeJavaRes/zip-cache/pxK5PXGPJSvz14yhh+tLQ0_nTuw=
git rm --cached app/build/intermediates/incremental/debug-mergeJavaRes/zip-cache/q5CqrOQ7G8owB5n3BJfEp38VObg=
git rm --cached app/build/intermediates/incremental/debug-mergeJavaRes/zip-cache/q9UYxEFLHwZ0Etml5eDe17bjiyc=
git rm --cached app/build/intermediates/incremental/debug-mergeJavaRes/zip-cache/qEfCwa9rX4pVG5grnug3m_kFccA=
git rm --cached app/build/intermediates/incremental/debug-mergeJavaRes/zip-cache/qqGsgeUR0cu6lYFCZgR+TOdvO4E=
git rm --cached app/build/intermediates/incremental/debug-mergeJavaRes/zip-cache/s7PAPEWyGFnQgrnkX9GARaPenos=
git rm --cached app/build/intermediates/incremental/debug-mergeJavaRes/zip-cache/thKc3sCCXXjkQtxuPjzpmqyzaCs=
git rm --cached app/build/intermediates/incremental/debug-mergeJavaRes/zip-cache/trQiw4JbQX+uCFSUGCPIY0oY1cQ=
git rm --cached app/build/intermediates/incremental/debug-mergeJavaRes/zip-cache/uArFtgb1SGK_qzfHsT1uUuX_db4=
git rm --cached app/build/intermediates/incremental/debug-mergeJavaRes/zip-cache/vln15IRBgG+tOXBJ3fEWGd2oKvY=
git rm --cached app/build/intermediates/incremental/debug-mergeJavaRes/zip-cache/wGp_E3CCK93KC9+kzdTjykZGpT4=
git rm --cached app/build/intermediates/incremental/debug-mergeJavaRes/zip-cache/wMH9Le+0Tg990O_nP5+HxLrJEgQ=
git rm --cached app/build/intermediates/incremental/debug-mergeJavaRes/zip-cache/wp5SC4b_WAalFAau8lmXFtJ163k=
git rm --cached app/build/intermediates/incremental/debug-mergeJavaRes/zip-cache/wq_FQQLw7zrhiirfCu17+gP8foI=
git rm --cached app/build/intermediates/incremental/debug-mergeJavaRes/zip-cache/yGO2y4wT_mVytVgO3QpZB7gjkwE=
git rm --cached app/build/intermediates/incremental/debug-mergeJavaRes/zip-cache/zdyH7Q_nIEUMnDXzehzbj3liehE=
git rm --cached app/build/intermediates/incremental/debug-mergeNativeLibs/merge-state
git rm --cached app/build/intermediates/incremental/debug-mergeNativeLibs/zip-cache/+Ct8x92_FWMsl2cfd7zkJFO3ZnQ=
git rm --cached app/build/intermediates/incremental/debug-mergeNativeLibs/zip-cache/+Eacf_SMdc7wXY+Xsaxvd0uEbkY=
git rm --cached app/build/intermediates/incremental/debug-mergeNativeLibs/zip-cache/02hzMNvGwIg2khdp2j4HnwS4wsE=
git rm --cached app/build/intermediates/incremental/debug-mergeNativeLibs/zip-cache/11_TK9_+DQd450hTe9K6twozdaI=
git rm --cached app/build/intermediates/incremental/debug-mergeNativeLibs/zip-cache/3eLpKFkt3JHLz8qaR3q9SFOCMJE=
git rm --cached app/build/intermediates/incremental/debug-mergeNativeLibs/zip-cache/3lkrxYON+icVv_G_Ry_ORS_r6lA=
git rm --cached app/build/intermediates/incremental/debug-mergeNativeLibs/zip-cache/3r_4A45birVST30Dc4jPw0QQTpE=
git rm --cached app/build/intermediates/incremental/debug-mergeNativeLibs/zip-cache/4tMdGY654UXRy_bmoZ4EWzGBOWE=
git rm --cached app/build/intermediates/incremental/debug-mergeNativeLibs/zip-cache/53CP9zBX4I8YqCcMTs22QTz4hcM=
git rm --cached app/build/intermediates/incremental/debug-mergeNativeLibs/zip-cache/72kDQhw5ALyRBWX5KbrJyjT0Ckc=
git rm --cached app/build/intermediates/incremental/debug-mergeNativeLibs/zip-cache/8FmYRrruUSbHYlx2ZHk_oLH8mdM=
git rm --cached app/build/intermediates/incremental/debug-mergeNativeLibs/zip-cache/BguPHJCvbI6yfLWll_q2KFGAydY=
git rm --cached app/build/intermediates/incremental/debug-mergeNativeLibs/zip-cache/BlevbGaYumtuA1d5IxDknml1q5w=
git rm --cached app/build/intermediates/incremental/debug-mergeNativeLibs/zip-cache/CG5L6oBY3aOAOEh2cKZQp+bpdcw=
git rm --cached app/build/intermediates/incremental/debug-mergeNativeLibs/zip-cache/E+yj20u2eCRTtUpttqAUVEBeO1U=
git rm --cached app/build/intermediates/incremental/debug-mergeNativeLibs/zip-cache/E4w4ebdUrjjkMtapZaAAqXOSgrs=
git rm --cached app/build/intermediates/incremental/debug-mergeNativeLibs/zip-cache/FobRWm5yrxJd+wdFQmOTCS67eAM=
git rm --cached app/build/intermediates/incremental/debug-mergeNativeLibs/zip-cache/G1pjCdxWKH0AHkj7pQPxmXO52aU=
git rm --cached app/build/intermediates/incremental/debug-mergeNativeLibs/zip-cache/GXpO2MgSyl_WvoqBZZNEUUGl0kM=
git rm --cached app/build/intermediates/incremental/debug-mergeNativeLibs/zip-cache/GocoNuSivdZz6VKqQHINhRfJ2jw=
git rm --cached app/build/intermediates/incremental/debug-mergeNativeLibs/zip-cache/KoK_crDqg1XEtzccdZe9wXXWyFk=
git rm --cached app/build/intermediates/incremental/debug-mergeNativeLibs/zip-cache/KohrFwl0fc5fy717cYBN9CtLJdY=
git rm --cached app/build/intermediates/incremental/debug-mergeNativeLibs/zip-cache/LWQ_rNI31EJO2xEUzedPphrELd4=
git rm --cached app/build/intermediates/incremental/debug-mergeNativeLibs/zip-cache/LjXElCWSy5vSIUosc3q8A3FJbz0=
git rm --cached app/build/intermediates/incremental/debug-mergeNativeLibs/zip-cache/LxWBpRRDMB9UoQWFoHuL1u4KPIc=
git rm --cached app/build/intermediates/incremental/debug-mergeNativeLibs/zip-cache/Mwi3n6dZxsaDpRApF8d1tKpRmkI=
git rm --cached app/build/intermediates/incremental/debug-mergeNativeLibs/zip-cache/QYUflg+nm5lBlWWLNbtYOZK76Fc=
git rm --cached app/build/intermediates/incremental/debug-mergeNativeLibs/zip-cache/T1fIZMNkOkDJN75RbCpeVZhTyaU=
git rm --cached app/build/intermediates/incremental/debug-mergeNativeLibs/zip-cache/T3SAKDf5q_UH8FFstEa05jjDCFo=
git rm --cached app/build/intermediates/incremental/debug-mergeNativeLibs/zip-cache/T7vFtfjIFKJz3p9JzlihgML6v44=
git rm --cached app/build/intermediates/incremental/debug-mergeNativeLibs/zip-cache/THQuE5JAiihtSsk1YARAXNcHr1I=
git rm --cached app/build/intermediates/incremental/debug-mergeNativeLibs/zip-cache/U1wMWIw7m8eL+CAYyhYvwEvLZ8I=
git rm --cached app/build/intermediates/incremental/debug-mergeNativeLibs/zip-cache/U8_yeXlEasBo1cCQYwZ9cFuNQeU=
git rm --cached app/build/intermediates/incremental/debug-mergeNativeLibs/zip-cache/W7zv41GAVSykiF8sdLqilbtQnoE=
git rm --cached app/build/intermediates/incremental/debug-mergeNativeLibs/zip-cache/WDAFa2xQl+oUFlinv8oVRlxGLmY=
git rm --cached app/build/intermediates/incremental/debug-mergeNativeLibs/zip-cache/X8LGyxdRJAeDKRK2RfnrRloR9_o=
git rm --cached app/build/intermediates/incremental/debug-mergeNativeLibs/zip-cache/Xsel8euWibo5wzmgEaWRAbcCOgs=
git rm --cached app/build/intermediates/incremental/debug-mergeNativeLibs/zip-cache/YFgw_HPNYwXsbgcg35ENRNXjcek=
git rm --cached app/build/intermediates/incremental/debug-mergeNativeLibs/zip-cache/ZQdg31S65uUrR9Rj5eJzryhWtgI=
git rm --cached app/build/intermediates/incremental/debug-mergeNativeLibs/zip-cache/_3J0lGdHoz41Sj2rqtRV8_wlwU0=
git rm --cached app/build/intermediates/incremental/debug-mergeNativeLibs/zip-cache/_4QpE8KKtu3tWVnKFUYmvVIkxV4=
git rm --cached app/build/intermediates/incremental/debug-mergeNativeLibs/zip-cache/_5VM2ZIT1GO8Q2U5lsJe8tqHkAM=
git rm --cached app/build/intermediates/incremental/debug-mergeNativeLibs/zip-cache/aK_NEcr2foDmc9Bi_uxpCc6rH0o=
git rm --cached app/build/intermediates/incremental/debug-mergeNativeLibs/zip-cache/avL2NrFgeG9oVy34xMxDvnZstXk=
git rm --cached app/build/intermediates/incremental/debug-mergeNativeLibs/zip-cache/cbWZeUhgcFoz6pWg_tCvFQ4mH0g=
git rm --cached app/build/intermediates/incremental/debug-mergeNativeLibs/zip-cache/dk03fbRkqzDWJb7U05muUdm3oWA=
git rm --cached app/build/intermediates/incremental/debug-mergeNativeLibs/zip-cache/elmtLe8O8YoeqmgQ+56Qna3zhjk=
git rm --cached app/build/intermediates/incremental/debug-mergeNativeLibs/zip-cache/i5oD1AreodMXyUAnk8xW49QqY8U=
git rm --cached app/build/intermediates/incremental/debug-mergeNativeLibs/zip-cache/m6aQboSqOdlFKxO7kMb2CFaDlSQ=
git rm --cached app/build/intermediates/incremental/debug-mergeNativeLibs/zip-cache/nczDUoIrtAM6EPBwCnsG7_ipb48=
git rm --cached app/build/intermediates/incremental/debug-mergeNativeLibs/zip-cache/o1U7+Mh45iCVb+Kpx0tB0IJSIDU=
git rm --cached app/build/intermediates/incremental/debug-mergeNativeLibs/zip-cache/ocO94zrF+F6whrUpkUCPk8Z6UFs=
git rm --cached app/build/intermediates/incremental/debug-mergeNativeLibs/zip-cache/peXu2uAflMypeqU60NnuUEumSz4=
git rm --cached app/build/intermediates/incremental/debug-mergeNativeLibs/zip-cache/pxK5PXGPJSvz14yhh+tLQ0_nTuw=
git rm --cached app/build/intermediates/incremental/debug-mergeNativeLibs/zip-cache/q5CqrOQ7G8owB5n3BJfEp38VObg=
git rm --cached app/build/intermediates/incremental/debug-mergeNativeLibs/zip-cache/q9UYxEFLHwZ0Etml5eDe17bjiyc=
git rm --cached app/build/intermediates/incremental/debug-mergeNativeLibs/zip-cache/qEfCwa9rX4pVG5grnug3m_kFccA=
git rm --cached app/build/intermediates/incremental/debug-mergeNativeLibs/zip-cache/qqGsgeUR0cu6lYFCZgR+TOdvO4E=
git rm --cached app/build/intermediates/incremental/debug-mergeNativeLibs/zip-cache/s7PAPEWyGFnQgrnkX9GARaPenos=
git rm --cached app/build/intermediates/incremental/debug-mergeNativeLibs/zip-cache/thKc3sCCXXjkQtxuPjzpmqyzaCs=
git rm --cached app/build/intermediates/incremental/debug-mergeNativeLibs/zip-cache/trQiw4JbQX+uCFSUGCPIY0oY1cQ=
git rm --cached app/build/intermediates/incremental/debug-mergeNativeLibs/zip-cache/uArFtgb1SGK_qzfHsT1uUuX_db4=
git rm --cached app/build/intermediates/incremental/debug-mergeNativeLibs/zip-cache/vln15IRBgG+tOXBJ3fEWGd2oKvY=
git rm --cached app/build/intermediates/incremental/debug-mergeNativeLibs/zip-cache/wGp_E3CCK93KC9+kzdTjykZGpT4=
git rm --cached app/build/intermediates/incremental/debug-mergeNativeLibs/zip-cache/wMH9Le+0Tg990O_nP5+HxLrJEgQ=
git rm --cached app/build/intermediates/incremental/debug-mergeNativeLibs/zip-cache/wp5SC4b_WAalFAau8lmXFtJ163k=
git rm --cached app/build/intermediates/incremental/debug-mergeNativeLibs/zip-cache/wq_FQQLw7zrhiirfCu17+gP8foI=
git rm --cached app/build/intermediates/incremental/debug-mergeNativeLibs/zip-cache/yGO2y4wT_mVytVgO3QpZB7gjkwE=
git rm --cached app/build/intermediates/incremental/debug-mergeNativeLibs/zip-cache/zdyH7Q_nIEUMnDXzehzbj3liehE=
git rm --cached app/build/intermediates/incremental/mergeDebugAssets/merger.xml
git rm --cached app/build/intermediates/incremental/mergeDebugJniLibFolders/merger.xml
git rm --cached app/build/intermediates/incremental/mergeDebugResources/compile-file-map.properties
git rm --cached app/build/intermediates/incremental/mergeDebugResources/merged.dir/values-af/values-af.xml
git rm --cached app/build/intermediates/incremental/mergeDebugResources/merged.dir/values-am/values-am.xml
git rm --cached app/build/intermediates/incremental/mergeDebugResources/merged.dir/values-ar/values-ar.xml
git rm --cached app/build/intermediates/incremental/mergeDebugResources/merged.dir/values-as/values-as.xml
git rm --cached app/build/intermediates/incremental/mergeDebugResources/merged.dir/values-az/values-az.xml
git rm --cached app/build/intermediates/incremental/mergeDebugResources/merged.dir/values-b+sr+Latn/values-b+sr+Latn.xml
git rm --cached app/build/intermediates/incremental/mergeDebugResources/merged.dir/values-be/values-be.xml
git rm --cached app/build/intermediates/incremental/mergeDebugResources/merged.dir/values-bg/values-bg.xml
git rm --cached app/build/intermediates/incremental/mergeDebugResources/merged.dir/values-bn/values-bn.xml
git rm --cached app/build/intermediates/incremental/mergeDebugResources/merged.dir/values-bs/values-bs.xml
git rm --cached app/build/intermediates/incremental/mergeDebugResources/merged.dir/values-ca/values-ca.xml
git rm --cached app/build/intermediates/incremental/mergeDebugResources/merged.dir/values-cs/values-cs.xml
git rm --cached app/build/intermediates/incremental/mergeDebugResources/merged.dir/values-da/values-da.xml
git rm --cached app/build/intermediates/incremental/mergeDebugResources/merged.dir/values-de/values-de.xml
git rm --cached app/build/intermediates/incremental/mergeDebugResources/merged.dir/values-el/values-el.xml
git rm --cached app/build/intermediates/incremental/mergeDebugResources/merged.dir/values-en-rAU/values-en-rAU.xml
git rm --cached app/build/intermediates/incremental/mergeDebugResources/merged.dir/values-en-rCA/values-en-rCA.xml
git rm --cached app/build/intermediates/incremental/mergeDebugResources/merged.dir/values-en-rGB/values-en-rGB.xml
git rm --cached app/build/intermediates/incremental/mergeDebugResources/merged.dir/values-en-rIN/values-en-rIN.xml
git rm --cached app/build/intermediates/incremental/mergeDebugResources/merged.dir/values-en-rXC/values-en-rXC.xml
git rm --cached app/build/intermediates/incremental/mergeDebugResources/merged.dir/values-es-rUS/values-es-rUS.xml
git rm --cached app/build/intermediates/incremental/mergeDebugResources/merged.dir/values-es/values-es.xml
git rm --cached app/build/intermediates/incremental/mergeDebugResources/merged.dir/values-et/values-et.xml
git rm --cached app/build/intermediates/incremental/mergeDebugResources/merged.dir/values-eu/values-eu.xml
git rm --cached app/build/intermediates/incremental/mergeDebugResources/merged.dir/values-fa/values-fa.xml
git rm --cached app/build/intermediates/incremental/mergeDebugResources/merged.dir/values-fi/values-fi.xml
git rm --cached app/build/intermediates/incremental/mergeDebugResources/merged.dir/values-fr-rCA/values-fr-rCA.xml
git rm --cached app/build/intermediates/incremental/mergeDebugResources/merged.dir/values-fr/values-fr.xml
git rm --cached app/build/intermediates/incremental/mergeDebugResources/merged.dir/values-gl/values-gl.xml
git rm --cached app/build/intermediates/incremental/mergeDebugResources/merged.dir/values-gu/values-gu.xml
git rm --cached app/build/intermediates/incremental/mergeDebugResources/merged.dir/values-h720dp-v13/values-h720dp-v13.xml
git rm --cached app/build/intermediates/incremental/mergeDebugResources/merged.dir/values-hdpi-v4/values-hdpi-v4.xml
git rm --cached app/build/intermediates/incremental/mergeDebugResources/merged.dir/values-hi/values-hi.xml
git rm --cached app/build/intermediates/incremental/mergeDebugResources/merged.dir/values-hr/values-hr.xml
git rm --cached app/build/intermediates/incremental/mergeDebugResources/merged.dir/values-hu/values-hu.xml
git rm --cached app/build/intermediates/incremental/mergeDebugResources/merged.dir/values-hy/values-hy.xml
git rm --cached app/build/intermediates/incremental/mergeDebugResources/merged.dir/values-in/values-in.xml
git rm --cached app/build/intermediates/incremental/mergeDebugResources/merged.dir/values-is/values-is.xml
git rm --cached app/build/intermediates/incremental/mergeDebugResources/merged.dir/values-it/values-it.xml
git rm --cached app/build/intermediates/incremental/mergeDebugResources/merged.dir/values-iw/values-iw.xml
git rm --cached app/build/intermediates/incremental/mergeDebugResources/merged.dir/values-ja/values-ja.xml
git rm --cached app/build/intermediates/incremental/mergeDebugResources/merged.dir/values-ka/values-ka.xml
git rm --cached app/build/intermediates/incremental/mergeDebugResources/merged.dir/values-kk/values-kk.xml
git rm --cached app/build/intermediates/incremental/mergeDebugResources/merged.dir/values-km/values-km.xml
git rm --cached app/build/intermediates/incremental/mergeDebugResources/merged.dir/values-kn/values-kn.xml
git rm --cached app/build/intermediates/incremental/mergeDebugResources/merged.dir/values-ko/values-ko.xml
git rm --cached app/build/intermediates/incremental/mergeDebugResources/merged.dir/values-ky/values-ky.xml
git rm --cached app/build/intermediates/incremental/mergeDebugResources/merged.dir/values-land/values-land.xml
git rm --cached app/build/intermediates/incremental/mergeDebugResources/merged.dir/values-large-v4/values-large-v4.xml
git rm --cached app/build/intermediates/incremental/mergeDebugResources/merged.dir/values-ldltr-v21/values-ldltr-v21.xml
git rm --cached app/build/intermediates/incremental/mergeDebugResources/merged.dir/values-lo/values-lo.xml
git rm --cached app/build/intermediates/incremental/mergeDebugResources/merged.dir/values-lt/values-lt.xml
git rm --cached app/build/intermediates/incremental/mergeDebugResources/merged.dir/values-lv/values-lv.xml
git rm --cached app/build/intermediates/incremental/mergeDebugResources/merged.dir/values-mk/values-mk.xml
git rm --cached app/build/intermediates/incremental/mergeDebugResources/merged.dir/values-ml/values-ml.xml
git rm --cached app/build/intermediates/incremental/mergeDebugResources/merged.dir/values-mn/values-mn.xml
git rm --cached app/build/intermediates/incremental/mergeDebugResources/merged.dir/values-mr/values-mr.xml
git rm --cached app/build/intermediates/incremental/mergeDebugResources/merged.dir/values-ms/values-ms.xml
git rm --cached app/build/intermediates/incremental/mergeDebugResources/merged.dir/values-my/values-my.xml
git rm --cached app/build/intermediates/incremental/mergeDebugResources/merged.dir/values-nb/values-nb.xml
git rm --cached app/build/intermediates/incremental/mergeDebugResources/merged.dir/values-ne/values-ne.xml
git rm --cached app/build/intermediates/incremental/mergeDebugResources/merged.dir/values-night-v8/values-night-v8.xml
git rm --cached app/build/intermediates/incremental/mergeDebugResources/merged.dir/values-nl/values-nl.xml
git rm --cached app/build/intermediates/incremental/mergeDebugResources/merged.dir/values-or/values-or.xml
git rm --cached app/build/intermediates/incremental/mergeDebugResources/merged.dir/values-pa/values-pa.xml
git rm --cached app/build/intermediates/incremental/mergeDebugResources/merged.dir/values-pl/values-pl.xml
git rm --cached app/build/intermediates/incremental/mergeDebugResources/merged.dir/values-port/values-port.xml
git rm --cached app/build/intermediates/incremental/mergeDebugResources/merged.dir/values-pt-rBR/values-pt-rBR.xml
git rm --cached app/build/intermediates/incremental/mergeDebugResources/merged.dir/values-pt-rPT/values-pt-rPT.xml
git rm --cached app/build/intermediates/incremental/mergeDebugResources/merged.dir/values-pt/values-pt.xml
git rm --cached app/build/intermediates/incremental/mergeDebugResources/merged.dir/values-ro/values-ro.xml
git rm --cached app/build/intermediates/incremental/mergeDebugResources/merged.dir/values-ru/values-ru.xml
git rm --cached app/build/intermediates/incremental/mergeDebugResources/merged.dir/values-si/values-si.xml
git rm --cached app/build/intermediates/incremental/mergeDebugResources/merged.dir/values-sk/values-sk.xml
git rm --cached app/build/intermediates/incremental/mergeDebugResources/merged.dir/values-sl/values-sl.xml
git rm --cached app/build/intermediates/incremental/mergeDebugResources/merged.dir/values-sq/values-sq.xml
git rm --cached app/build/intermediates/incremental/mergeDebugResources/merged.dir/values-sr/values-sr.xml
git rm --cached app/build/intermediates/incremental/mergeDebugResources/merged.dir/values-sv/values-sv.xml
git rm --cached app/build/intermediates/incremental/mergeDebugResources/merged.dir/values-sw/values-sw.xml
git rm --cached app/build/intermediates/incremental/mergeDebugResources/merged.dir/values-sw600dp-v13/values-sw600dp-v13.xml
git rm --cached app/build/intermediates/incremental/mergeDebugResources/merged.dir/values-ta/values-ta.xml
git rm --cached app/build/intermediates/incremental/mergeDebugResources/merged.dir/values-te/values-te.xml
git rm --cached app/build/intermediates/incremental/mergeDebugResources/merged.dir/values-th/values-th.xml
git rm --cached app/build/intermediates/incremental/mergeDebugResources/merged.dir/values-tl/values-tl.xml
git rm --cached app/build/intermediates/incremental/mergeDebugResources/merged.dir/values-tr/values-tr.xml
git rm --cached app/build/intermediates/incremental/mergeDebugResources/merged.dir/values-uk/values-uk.xml
git rm --cached app/build/intermediates/incremental/mergeDebugResources/merged.dir/values-ur/values-ur.xml
git rm --cached app/build/intermediates/incremental/mergeDebugResources/merged.dir/values-uz/values-uz.xml
git rm --cached app/build/intermediates/incremental/mergeDebugResources/merged.dir/values-v16/values-v16.xml
git rm --cached app/build/intermediates/incremental/mergeDebugResources/merged.dir/values-v17/values-v17.xml
git rm --cached app/build/intermediates/incremental/mergeDebugResources/merged.dir/values-v18/values-v18.xml
git rm --cached app/build/intermediates/incremental/mergeDebugResources/merged.dir/values-v21/values-v21.xml
git rm --cached app/build/intermediates/incremental/mergeDebugResources/merged.dir/values-v22/values-v22.xml
git rm --cached app/build/intermediates/incremental/mergeDebugResources/merged.dir/values-v23/values-v23.xml
git rm --cached app/build/intermediates/incremental/mergeDebugResources/merged.dir/values-v24/values-v24.xml
git rm --cached app/build/intermediates/incremental/mergeDebugResources/merged.dir/values-v25/values-v25.xml
git rm --cached app/build/intermediates/incremental/mergeDebugResources/merged.dir/values-v26/values-v26.xml
git rm --cached app/build/intermediates/incremental/mergeDebugResources/merged.dir/values-v28/values-v28.xml
git rm --cached app/build/intermediates/incremental/mergeDebugResources/merged.dir/values-vi/values-vi.xml
git rm --cached app/build/intermediates/incremental/mergeDebugResources/merged.dir/values-watch-v20/values-watch-v20.xml
git rm --cached app/build/intermediates/incremental/mergeDebugResources/merged.dir/values-watch-v21/values-watch-v21.xml
git rm --cached app/build/intermediates/incremental/mergeDebugResources/merged.dir/values-xlarge-v4/values-xlarge-v4.xml
git rm --cached app/build/intermediates/incremental/mergeDebugResources/merged.dir/values-zh-rCN/values-zh-rCN.xml
git rm --cached app/build/intermediates/incremental/mergeDebugResources/merged.dir/values-zh-rHK/values-zh-rHK.xml
git rm --cached app/build/intermediates/incremental/mergeDebugResources/merged.dir/values-zh-rTW/values-zh-rTW.xml
git rm --cached app/build/intermediates/incremental/mergeDebugResources/merged.dir/values-zu/values-zu.xml
git rm --cached app/build/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml
git rm --cached app/build/intermediates/incremental/mergeDebugResources/merger.xml
git rm --cached app/build/intermediates/incremental/mergeDebugResources/stripped.dir/layout/activity_main.xml
git rm --cached app/build/intermediates/incremental/mergeDebugResources/stripped.dir/layout/content_main.xml
git rm --cached app/build/intermediates/incremental/mergeDebugResources/stripped.dir/layout/form_list.xml
git rm --cached app/build/intermediates/incremental/mergeDebugResources/stripped.dir/layout/fragment_item.xml
git rm --cached app/build/intermediates/incremental/mergeDebugResources/stripped.dir/layout/list_field_layout.xml
git rm --cached app/build/intermediates/incremental/mergeDebugResources/stripped.dir/layout/list_item.xml
git rm --cached app/build/intermediates/incremental/mergeDebugResources/stripped.dir/layout/list_item_header.xml
git rm --cached app/build/intermediates/incremental/mergeDebugResources/stripped.dir/layout/list_item_textview.xml
git rm --cached app/build/intermediates/incremental/mergeDebugResources/stripped.dir/layout/tool_alphaedit_boolean.xml
git rm --cached app/build/intermediates/incremental/mergeDebugResources/stripped.dir/layout/tool_alphaedit_date.xml
git rm --cached app/build/intermediates/incremental/mergeDebugResources/stripped.dir/layout/tool_alphaedit_finisher_fromxml.xml
git rm --cached app/build/intermediates/incremental/mergeDebugResources/stripped.dir/layout/tool_alphaedit_text.xml
git rm --cached app/build/intermediates/incremental/mergeDebugShaders/merger.xml
git rm --cached app/build/intermediates/incremental/packageDebug/tmp/debug/dex-renamer-state.txt
git rm --cached app/build/intermediates/instant_app_manifest/debug/AndroidManifest.xml
git rm --cached app/build/intermediates/instant_app_manifest/debug/output.json
git rm --cached app/build/intermediates/javac/debug/classes/androidx/databinding/DataBinderMapperImpl.class
git rm --cached app/build/intermediates/javac/debug/classes/androidx/databinding/DataBindingComponent.class
git rm --cached app/build/intermediates/javac/debug/classes/androidx/databinding/library/baseAdapters/BR.class
git rm --cached app/build/intermediates/javac/debug/classes/es/jcyl/ita/frmdrd/BR.class
git rm --cached app/build/intermediates/javac/debug/classes/es/jcyl/ita/frmdrd/BuildConfig.class
git rm --cached app/build/intermediates/javac/debug/classes/es/jcyl/ita/frmdrd/DataBinderMapperImpl$InnerBrLookup.class
git rm --cached app/build/intermediates/javac/debug/classes/es/jcyl/ita/frmdrd/DataBinderMapperImpl$InnerLayoutIdLookup.class
git rm --cached app/build/intermediates/javac/debug/classes/es/jcyl/ita/frmdrd/DataBinderMapperImpl.class
git rm --cached app/build/intermediates/javac/debug/classes/es/jcyl/ita/frmdrd/DataBindingInfo.class
git rm --cached app/build/intermediates/javac/debug/classes/es/jcyl/ita/frmdrd/DiComponent.class
git rm --cached app/build/intermediates/javac/debug/classes/es/jcyl/ita/frmdrd/FormListFragment$1.class
git rm --cached app/build/intermediates/javac/debug/classes/es/jcyl/ita/frmdrd/FormListFragment$OnListFragmentInteractionListener.class
git rm --cached app/build/intermediates/javac/debug/classes/es/jcyl/ita/frmdrd/FormListFragment.class
git rm --cached app/build/intermediates/javac/debug/classes/es/jcyl/ita/frmdrd/MainActivity$1.class
git rm --cached app/build/intermediates/javac/debug/classes/es/jcyl/ita/frmdrd/MainActivity.class
git rm --cached app/build/intermediates/javac/debug/classes/es/jcyl/ita/frmdrd/MyItemRecyclerViewAdapter$1.class
git rm --cached app/build/intermediates/javac/debug/classes/es/jcyl/ita/frmdrd/MyItemRecyclerViewAdapter$ViewHolder.class
git rm --cached app/build/intermediates/javac/debug/classes/es/jcyl/ita/frmdrd/MyItemRecyclerViewAdapter.class
git rm --cached app/build/intermediates/javac/debug/classes/es/jcyl/ita/frmdrd/NavigationManager.class
git rm --cached app/build/intermediates/javac/debug/classes/es/jcyl/ita/frmdrd/UserFormAlphaEditActivity.class
git rm --cached app/build/intermediates/javac/debug/classes/es/jcyl/ita/frmdrd/configuration/DataBindings.class
git rm --cached app/build/intermediates/javac/debug/classes/es/jcyl/ita/frmdrd/configuration/FormConfigHandler.class
git rm --cached app/build/intermediates/javac/debug/classes/es/jcyl/ita/frmdrd/configuration/parser/DummyFormConfigParser.class
git rm --cached app/build/intermediates/javac/debug/classes/es/jcyl/ita/frmdrd/configuration/parser/FormConfigParser.class
git rm --cached app/build/intermediates/javac/debug/classes/es/jcyl/ita/frmdrd/configuration/parser/JSONFormConfigParser.class
git rm --cached app/build/intermediates/javac/debug/classes/es/jcyl/ita/frmdrd/configuration/parser/TableFormConfigParser.class
git rm --cached app/build/intermediates/javac/debug/classes/es/jcyl/ita/frmdrd/configuration/parser/XMLFormConfigParser.class
git rm --cached app/build/intermediates/javac/debug/classes/es/jcyl/ita/frmdrd/context/AbstractContext.class
git rm --cached app/build/intermediates/javac/debug/classes/es/jcyl/ita/frmdrd/context/CompositeContext.class
git rm --cached app/build/intermediates/javac/debug/classes/es/jcyl/ita/frmdrd/context/Context.class
git rm --cached app/build/intermediates/javac/debug/classes/es/jcyl/ita/frmdrd/context/ContextException.class
git rm --cached app/build/intermediates/javac/debug/classes/es/jcyl/ita/frmdrd/context/ContextProvider.class
git rm --cached app/build/intermediates/javac/debug/classes/es/jcyl/ita/frmdrd/context/JexlTest.class
git rm --cached app/build/intermediates/javac/debug/classes/es/jcyl/ita/frmdrd/context/OrderedCompositeContext.class
git rm --cached app/build/intermediates/javac/debug/classes/es/jcyl/ita/frmdrd/context/impl/BasicContext.class
git rm --cached app/build/intermediates/javac/debug/classes/es/jcyl/ita/frmdrd/context/impl/CalendarField.class
git rm --cached app/build/intermediates/javac/debug/classes/es/jcyl/ita/frmdrd/context/impl/CalendarOperation$1.class
git rm --cached app/build/intermediates/javac/debug/classes/es/jcyl/ita/frmdrd/context/impl/CalendarOperation$OperType.class
git rm --cached app/build/intermediates/javac/debug/classes/es/jcyl/ita/frmdrd/context/impl/CalendarOperation.class
git rm --cached app/build/intermediates/javac/debug/classes/es/jcyl/ita/frmdrd/context/impl/DateExpressionInterpreter.class
git rm --cached app/build/intermediates/javac/debug/classes/es/jcyl/ita/frmdrd/context/impl/DateTimeContext$1.class
git rm --cached app/build/intermediates/javac/debug/classes/es/jcyl/ita/frmdrd/context/impl/DateTimeContext.class
git rm --cached app/build/intermediates/javac/debug/classes/es/jcyl/ita/frmdrd/context/impl/DynamicListContext.class
git rm --cached app/build/intermediates/javac/debug/classes/es/jcyl/ita/frmdrd/context/impl/FormContext.class
git rm --cached app/build/intermediates/javac/debug/classes/es/jcyl/ita/frmdrd/context/reader/ContextReader.class
git rm --cached app/build/intermediates/javac/debug/classes/es/jcyl/ita/frmdrd/context/reader/DBContextReader.class
git rm --cached app/build/intermediates/javac/debug/classes/es/jcyl/ita/frmdrd/dao/collection/PaginatedList.class
git rm --cached app/build/intermediates/javac/debug/classes/es/jcyl/ita/frmdrd/dao/collection/PaginationInfo.class
git rm --cached app/build/intermediates/javac/debug/classes/es/jcyl/ita/frmdrd/dao/engine/jdbc/QueryEngine$RowMapper.class
git rm --cached app/build/intermediates/javac/debug/classes/es/jcyl/ita/frmdrd/dao/engine/jdbc/QueryEngine.class
git rm --cached app/build/intermediates/javac/debug/classes/es/jcyl/ita/frmdrd/dao/loader/EntityLoader.class
git rm --cached app/build/intermediates/javac/debug/classes/es/jcyl/ita/frmdrd/dao/persister/Entity.class
git rm --cached app/build/intermediates/javac/debug/classes/es/jcyl/ita/frmdrd/dao/persister/EntityMeta.class
git rm --cached app/build/intermediates/javac/debug/classes/es/jcyl/ita/frmdrd/dao/persister/EntityPersister.class
git rm --cached app/build/intermediates/javac/debug/classes/es/jcyl/ita/frmdrd/dao/persister/PersisterException.class
git rm --cached app/build/intermediates/javac/debug/classes/es/jcyl/ita/frmdrd/dao/persister/jdbc/ParsedQuery.class
git rm --cached app/build/intermediates/javac/debug/classes/es/jcyl/ita/frmdrd/dao/persister/jdbc/SQLEntityPersiser.class
git rm --cached app/build/intermediates/javac/debug/classes/es/jcyl/ita/frmdrd/dao/sources/DBSourceDescriptor.class
git rm --cached app/build/intermediates/javac/debug/classes/es/jcyl/ita/frmdrd/dao/sources/FileSourceDescriptor.class
git rm --cached app/build/intermediates/javac/debug/classes/es/jcyl/ita/frmdrd/dao/sources/SampleSourceDescriptor.class
git rm --cached app/build/intermediates/javac/debug/classes/es/jcyl/ita/frmdrd/dao/sources/SourceDescriptor.class
git rm --cached app/build/intermediates/javac/debug/classes/es/jcyl/ita/frmdrd/data/KeyValuePair.class
git rm --cached app/build/intermediates/javac/debug/classes/es/jcyl/ita/frmdrd/data/SavedData.class
git rm --cached app/build/intermediates/javac/debug/classes/es/jcyl/ita/frmdrd/dummy/DummyContent$FormListItem.class
git rm --cached app/build/intermediates/javac/debug/classes/es/jcyl/ita/frmdrd/dummy/DummyContent.class
git rm --cached app/build/intermediates/javac/debug/classes/es/jcyl/ita/frmdrd/lifecycle/Lifecycle.class
git rm --cached app/build/intermediates/javac/debug/classes/es/jcyl/ita/frmdrd/lifecycle/PhaseEvent.class
git rm --cached app/build/intermediates/javac/debug/classes/es/jcyl/ita/frmdrd/lifecycle/PhaseListener.class
git rm --cached app/build/intermediates/javac/debug/classes/es/jcyl/ita/frmdrd/lifecycle/phase/BuildFormContextPhase.class
git rm --cached app/build/intermediates/javac/debug/classes/es/jcyl/ita/frmdrd/lifecycle/phase/BuildParamContextPhase.class
git rm --cached app/build/intermediates/javac/debug/classes/es/jcyl/ita/frmdrd/lifecycle/phase/LoadLocalContextsPhase.class
git rm --cached app/build/intermediates/javac/debug/classes/es/jcyl/ita/frmdrd/lifecycle/phase/Phase$PhaseId.class
git rm --cached app/build/intermediates/javac/debug/classes/es/jcyl/ita/frmdrd/lifecycle/phase/Phase.class
git rm --cached app/build/intermediates/javac/debug/classes/es/jcyl/ita/frmdrd/lifecycle/phase/ProcessValidationsPhase.class
git rm --cached app/build/intermediates/javac/debug/classes/es/jcyl/ita/frmdrd/lifecycle/phase/RenderViewPhase.class
git rm --cached app/build/intermediates/javac/debug/classes/es/jcyl/ita/frmdrd/processors/GroovyProcessor$1.class
git rm --cached app/build/intermediates/javac/debug/classes/es/jcyl/ita/frmdrd/processors/GroovyProcessor$EvalResult.class
git rm --cached app/build/intermediates/javac/debug/classes/es/jcyl/ita/frmdrd/processors/GroovyProcessor.class
git rm --cached app/build/intermediates/javac/debug/classes/es/jcyl/ita/frmdrd/processors/JexlProcessor.class
git rm --cached app/build/intermediates/javac/debug/classes/es/jcyl/ita/frmdrd/render/AbstractFieldRenderer.class
git rm --cached app/build/intermediates/javac/debug/classes/es/jcyl/ita/frmdrd/render/CheckBoxFieldRenderer$1.class
git rm --cached app/build/intermediates/javac/debug/classes/es/jcyl/ita/frmdrd/render/CheckBoxFieldRenderer.class
git rm --cached app/build/intermediates/javac/debug/classes/es/jcyl/ita/frmdrd/render/DateFieldRenderer$1.class
git rm --cached app/build/intermediates/javac/debug/classes/es/jcyl/ita/frmdrd/render/DateFieldRenderer$2.class
git rm --cached app/build/intermediates/javac/debug/classes/es/jcyl/ita/frmdrd/render/DateFieldRenderer$3.class
git rm --cached app/build/intermediates/javac/debug/classes/es/jcyl/ita/frmdrd/render/DateFieldRenderer.class
git rm --cached app/build/intermediates/javac/debug/classes/es/jcyl/ita/frmdrd/render/FormRenderer$1.class
git rm --cached app/build/intermediates/javac/debug/classes/es/jcyl/ita/frmdrd/render/FormRenderer$2.class
git rm --cached app/build/intermediates/javac/debug/classes/es/jcyl/ita/frmdrd/render/FormRenderer$3.class
git rm --cached app/build/intermediates/javac/debug/classes/es/jcyl/ita/frmdrd/render/FormRenderer.class
git rm --cached app/build/intermediates/javac/debug/classes/es/jcyl/ita/frmdrd/render/ListEntityAdapter$1.class
git rm --cached app/build/intermediates/javac/debug/classes/es/jcyl/ita/frmdrd/render/ListEntityAdapter$ViewHolder.class
git rm --cached app/build/intermediates/javac/debug/classes/es/jcyl/ita/frmdrd/render/ListEntityAdapter.class
git rm --cached app/build/intermediates/javac/debug/classes/es/jcyl/ita/frmdrd/render/ListEntityDialog$1.class
git rm --cached app/build/intermediates/javac/debug/classes/es/jcyl/ita/frmdrd/render/ListEntityDialog.class
git rm --cached app/build/intermediates/javac/debug/classes/es/jcyl/ita/frmdrd/render/OnChangeFieldInterceptor.class
git rm --cached app/build/intermediates/javac/debug/classes/es/jcyl/ita/frmdrd/render/RendererFactory.class
git rm --cached app/build/intermediates/javac/debug/classes/es/jcyl/ita/frmdrd/render/TableFieldRenderer$1.class
git rm --cached app/build/intermediates/javac/debug/classes/es/jcyl/ita/frmdrd/render/TableFieldRenderer.class
git rm --cached app/build/intermediates/javac/debug/classes/es/jcyl/ita/frmdrd/render/TextFieldRenderer$1.class
git rm --cached app/build/intermediates/javac/debug/classes/es/jcyl/ita/frmdrd/render/TextFieldRenderer.class
git rm --cached app/build/intermediates/javac/debug/classes/es/jcyl/ita/frmdrd/render/UIFieldRenderer.class
git rm --cached app/build/intermediates/javac/debug/classes/es/jcyl/ita/frmdrd/ui/form/UIComponent.class
git rm --cached app/build/intermediates/javac/debug/classes/es/jcyl/ita/frmdrd/ui/form/UIField$TYPE.class
git rm --cached app/build/intermediates/javac/debug/classes/es/jcyl/ita/frmdrd/ui/form/UIField.class
git rm --cached app/build/intermediates/javac/debug/classes/es/jcyl/ita/frmdrd/ui/form/UIForm.class
git rm --cached app/build/intermediates/javac/debug/classes/es/jcyl/ita/frmdrd/ui/form/UITab.class
git rm --cached app/build/intermediates/javac/debug/classes/es/jcyl/ita/frmdrd/util/DataUtils.class
git rm --cached app/build/intermediates/manifest_merge_blame_file/debug/manifest-merger-blame-debug-report.txt
git rm --cached app/build/intermediates/merged_java_res/debug/out.jar
git rm --cached app/build/intermediates/merged_manifests/debug/AndroidManifest.xml
git rm --cached app/build/intermediates/merged_manifests/debug/output.json
git rm --cached app/build/intermediates/metadata_feature_manifest/debug/metadata-feature/output.json
git rm --cached app/build/intermediates/navigation_json/debug/navigation.json
git rm --cached app/build/intermediates/processed_res/debug/out/output.json
git rm --cached app/build/intermediates/processed_res/debug/out/resources-debug.ap_
git rm --cached app/build/intermediates/project_dex_archive/debug/out/androidx/databinding/DataBinderMapperImpl.dex
git rm --cached app/build/intermediates/project_dex_archive/debug/out/androidx/databinding/DataBindingComponent.dex
git rm --cached app/build/intermediates/project_dex_archive/debug/out/androidx/databinding/library/baseAdapters/BR.dex
git rm --cached app/build/intermediates/project_dex_archive/debug/out/bc46cee1452bdf75c65327386338e0b3ce13e2cc037be4a9ef38908e284f72cb_0.jar
git rm --cached app/build/intermediates/project_dex_archive/debug/out/bc46cee1452bdf75c65327386338e0b3ce13e2cc037be4a9ef38908e284f72cb_1.jar
git rm --cached app/build/intermediates/project_dex_archive/debug/out/bc46cee1452bdf75c65327386338e0b3ce13e2cc037be4a9ef38908e284f72cb_2.jar
git rm --cached app/build/intermediates/project_dex_archive/debug/out/bc46cee1452bdf75c65327386338e0b3ce13e2cc037be4a9ef38908e284f72cb_3.jar
git rm --cached app/build/intermediates/project_dex_archive/debug/out/es/jcyl/ita/frmdrd/BR.dex
git rm --cached app/build/intermediates/project_dex_archive/debug/out/es/jcyl/ita/frmdrd/BuildConfig.dex
git rm --cached app/build/intermediates/project_dex_archive/debug/out/es/jcyl/ita/frmdrd/DataBinderMapperImpl$InnerBrLookup.dex
git rm --cached app/build/intermediates/project_dex_archive/debug/out/es/jcyl/ita/frmdrd/DataBinderMapperImpl$InnerLayoutIdLookup.dex
git rm --cached app/build/intermediates/project_dex_archive/debug/out/es/jcyl/ita/frmdrd/DataBinderMapperImpl.dex
git rm --cached app/build/intermediates/project_dex_archive/debug/out/es/jcyl/ita/frmdrd/DataBindingInfo.dex
git rm --cached app/build/intermediates/project_dex_archive/debug/out/es/jcyl/ita/frmdrd/DiComponent.dex
git rm --cached app/build/intermediates/project_dex_archive/debug/out/es/jcyl/ita/frmdrd/FormListFragment$1.dex
git rm --cached app/build/intermediates/project_dex_archive/debug/out/es/jcyl/ita/frmdrd/FormListFragment$OnListFragmentInteractionListener.dex
git rm --cached app/build/intermediates/project_dex_archive/debug/out/es/jcyl/ita/frmdrd/FormListFragment.dex
git rm --cached app/build/intermediates/project_dex_archive/debug/out/es/jcyl/ita/frmdrd/MainActivity$1.dex
git rm --cached app/build/intermediates/project_dex_archive/debug/out/es/jcyl/ita/frmdrd/MainActivity.dex
git rm --cached app/build/intermediates/project_dex_archive/debug/out/es/jcyl/ita/frmdrd/MyItemRecyclerViewAdapter$1.dex
git rm --cached app/build/intermediates/project_dex_archive/debug/out/es/jcyl/ita/frmdrd/MyItemRecyclerViewAdapter$ViewHolder.dex
git rm --cached app/build/intermediates/project_dex_archive/debug/out/es/jcyl/ita/frmdrd/MyItemRecyclerViewAdapter.dex
git rm --cached app/build/intermediates/project_dex_archive/debug/out/es/jcyl/ita/frmdrd/NavigationManager.dex
git rm --cached app/build/intermediates/project_dex_archive/debug/out/es/jcyl/ita/frmdrd/UserFormAlphaEditActivity.dex
git rm --cached app/build/intermediates/project_dex_archive/debug/out/es/jcyl/ita/frmdrd/configuration/DataBindings.dex
git rm --cached app/build/intermediates/project_dex_archive/debug/out/es/jcyl/ita/frmdrd/configuration/FormConfigHandler.dex
git rm --cached app/build/intermediates/project_dex_archive/debug/out/es/jcyl/ita/frmdrd/configuration/parser/DummyFormConfigParser.dex
git rm --cached app/build/intermediates/project_dex_archive/debug/out/es/jcyl/ita/frmdrd/configuration/parser/FormConfigParser.dex
git rm --cached app/build/intermediates/project_dex_archive/debug/out/es/jcyl/ita/frmdrd/configuration/parser/JSONFormConfigParser.dex
git rm --cached app/build/intermediates/project_dex_archive/debug/out/es/jcyl/ita/frmdrd/configuration/parser/TableFormConfigParser.dex
git rm --cached app/build/intermediates/project_dex_archive/debug/out/es/jcyl/ita/frmdrd/configuration/parser/XMLFormConfigParser.dex
git rm --cached app/build/intermediates/project_dex_archive/debug/out/es/jcyl/ita/frmdrd/context/AbstractContext.dex
git rm --cached app/build/intermediates/project_dex_archive/debug/out/es/jcyl/ita/frmdrd/context/CompositeContext.dex
git rm --cached app/build/intermediates/project_dex_archive/debug/out/es/jcyl/ita/frmdrd/context/Context.dex
git rm --cached app/build/intermediates/project_dex_archive/debug/out/es/jcyl/ita/frmdrd/context/ContextException.dex
git rm --cached app/build/intermediates/project_dex_archive/debug/out/es/jcyl/ita/frmdrd/context/ContextProvider.dex
git rm --cached app/build/intermediates/project_dex_archive/debug/out/es/jcyl/ita/frmdrd/context/JexlTest.dex
git rm --cached app/build/intermediates/project_dex_archive/debug/out/es/jcyl/ita/frmdrd/context/OrderedCompositeContext.dex
git rm --cached app/build/intermediates/project_dex_archive/debug/out/es/jcyl/ita/frmdrd/context/impl/BasicContext.dex
git rm --cached app/build/intermediates/project_dex_archive/debug/out/es/jcyl/ita/frmdrd/context/impl/CalendarField.dex
git rm --cached app/build/intermediates/project_dex_archive/debug/out/es/jcyl/ita/frmdrd/context/impl/CalendarOperation$1.dex
git rm --cached app/build/intermediates/project_dex_archive/debug/out/es/jcyl/ita/frmdrd/context/impl/CalendarOperation$OperType.dex
git rm --cached app/build/intermediates/project_dex_archive/debug/out/es/jcyl/ita/frmdrd/context/impl/CalendarOperation.dex
git rm --cached app/build/intermediates/project_dex_archive/debug/out/es/jcyl/ita/frmdrd/context/impl/DateExpressionInterpreter.dex
git rm --cached app/build/intermediates/project_dex_archive/debug/out/es/jcyl/ita/frmdrd/context/impl/DateTimeContext$1.dex
git rm --cached app/build/intermediates/project_dex_archive/debug/out/es/jcyl/ita/frmdrd/context/impl/DateTimeContext.dex
git rm --cached app/build/intermediates/project_dex_archive/debug/out/es/jcyl/ita/frmdrd/context/impl/DynamicListContext.dex
git rm --cached app/build/intermediates/project_dex_archive/debug/out/es/jcyl/ita/frmdrd/context/impl/FormContext.dex
git rm --cached app/build/intermediates/project_dex_archive/debug/out/es/jcyl/ita/frmdrd/context/reader/ContextReader.dex
git rm --cached app/build/intermediates/project_dex_archive/debug/out/es/jcyl/ita/frmdrd/context/reader/DBContextReader.dex
git rm --cached app/build/intermediates/project_dex_archive/debug/out/es/jcyl/ita/frmdrd/dao/collection/PaginatedList.dex
git rm --cached app/build/intermediates/project_dex_archive/debug/out/es/jcyl/ita/frmdrd/dao/collection/PaginationInfo.dex
git rm --cached app/build/intermediates/project_dex_archive/debug/out/es/jcyl/ita/frmdrd/dao/engine/jdbc/QueryEngine$RowMapper.dex
git rm --cached app/build/intermediates/project_dex_archive/debug/out/es/jcyl/ita/frmdrd/dao/engine/jdbc/QueryEngine.dex
git rm --cached app/build/intermediates/project_dex_archive/debug/out/es/jcyl/ita/frmdrd/dao/loader/EntityLoader.dex
git rm --cached app/build/intermediates/project_dex_archive/debug/out/es/jcyl/ita/frmdrd/dao/persister/Entity.dex
git rm --cached app/build/intermediates/project_dex_archive/debug/out/es/jcyl/ita/frmdrd/dao/persister/EntityMeta.dex
git rm --cached app/build/intermediates/project_dex_archive/debug/out/es/jcyl/ita/frmdrd/dao/persister/EntityPersister.dex
git rm --cached app/build/intermediates/project_dex_archive/debug/out/es/jcyl/ita/frmdrd/dao/persister/PersisterException.dex
git rm --cached app/build/intermediates/project_dex_archive/debug/out/es/jcyl/ita/frmdrd/dao/persister/jdbc/ParsedQuery.dex
git rm --cached app/build/intermediates/project_dex_archive/debug/out/es/jcyl/ita/frmdrd/dao/persister/jdbc/SQLEntityPersiser.dex
git rm --cached app/build/intermediates/project_dex_archive/debug/out/es/jcyl/ita/frmdrd/dao/sources/DBSourceDescriptor.dex
git rm --cached app/build/intermediates/project_dex_archive/debug/out/es/jcyl/ita/frmdrd/dao/sources/FileSourceDescriptor.dex
git rm --cached app/build/intermediates/project_dex_archive/debug/out/es/jcyl/ita/frmdrd/dao/sources/SampleSourceDescriptor.dex
git rm --cached app/build/intermediates/project_dex_archive/debug/out/es/jcyl/ita/frmdrd/dao/sources/SourceDescriptor.dex
git rm --cached app/build/intermediates/project_dex_archive/debug/out/es/jcyl/ita/frmdrd/data/KeyValuePair.dex
git rm --cached app/build/intermediates/project_dex_archive/debug/out/es/jcyl/ita/frmdrd/data/SavedData.dex
git rm --cached app/build/intermediates/project_dex_archive/debug/out/es/jcyl/ita/frmdrd/dummy/DummyContent$FormListItem.dex
git rm --cached app/build/intermediates/project_dex_archive/debug/out/es/jcyl/ita/frmdrd/dummy/DummyContent.dex
git rm --cached app/build/intermediates/project_dex_archive/debug/out/es/jcyl/ita/frmdrd/lifecycle/Lifecycle.dex
git rm --cached app/build/intermediates/project_dex_archive/debug/out/es/jcyl/ita/frmdrd/lifecycle/PhaseEvent.dex
git rm --cached app/build/intermediates/project_dex_archive/debug/out/es/jcyl/ita/frmdrd/lifecycle/PhaseListener.dex
git rm --cached app/build/intermediates/project_dex_archive/debug/out/es/jcyl/ita/frmdrd/lifecycle/phase/BuildFormContextPhase.dex
git rm --cached app/build/intermediates/project_dex_archive/debug/out/es/jcyl/ita/frmdrd/lifecycle/phase/BuildParamContextPhase.dex
git rm --cached app/build/intermediates/project_dex_archive/debug/out/es/jcyl/ita/frmdrd/lifecycle/phase/LoadLocalContextsPhase.dex
git rm --cached app/build/intermediates/project_dex_archive/debug/out/es/jcyl/ita/frmdrd/lifecycle/phase/Phase$PhaseId.dex
git rm --cached app/build/intermediates/project_dex_archive/debug/out/es/jcyl/ita/frmdrd/lifecycle/phase/Phase.dex
git rm --cached app/build/intermediates/project_dex_archive/debug/out/es/jcyl/ita/frmdrd/lifecycle/phase/ProcessValidationsPhase.dex
git rm --cached app/build/intermediates/project_dex_archive/debug/out/es/jcyl/ita/frmdrd/lifecycle/phase/RenderViewPhase.dex
git rm --cached app/build/intermediates/project_dex_archive/debug/out/es/jcyl/ita/frmdrd/processors/GroovyProcessor$1.dex
git rm --cached app/build/intermediates/project_dex_archive/debug/out/es/jcyl/ita/frmdrd/processors/GroovyProcessor$EvalResult.dex
git rm --cached app/build/intermediates/project_dex_archive/debug/out/es/jcyl/ita/frmdrd/processors/GroovyProcessor.dex
git rm --cached app/build/intermediates/project_dex_archive/debug/out/es/jcyl/ita/frmdrd/processors/JexlProcessor.dex
git rm --cached app/build/intermediates/project_dex_archive/debug/out/es/jcyl/ita/frmdrd/render/AbstractFieldRenderer.dex
git rm --cached app/build/intermediates/project_dex_archive/debug/out/es/jcyl/ita/frmdrd/render/CheckBoxFieldRenderer$1.dex
git rm --cached app/build/intermediates/project_dex_archive/debug/out/es/jcyl/ita/frmdrd/render/CheckBoxFieldRenderer.dex
git rm --cached app/build/intermediates/project_dex_archive/debug/out/es/jcyl/ita/frmdrd/render/DateFieldRenderer$1.dex
git rm --cached app/build/intermediates/project_dex_archive/debug/out/es/jcyl/ita/frmdrd/render/DateFieldRenderer$2.dex
git rm --cached app/build/intermediates/project_dex_archive/debug/out/es/jcyl/ita/frmdrd/render/DateFieldRenderer$3.dex
git rm --cached app/build/intermediates/project_dex_archive/debug/out/es/jcyl/ita/frmdrd/render/DateFieldRenderer.dex
git rm --cached app/build/intermediates/project_dex_archive/debug/out/es/jcyl/ita/frmdrd/render/FormRenderer$1.dex
git rm --cached app/build/intermediates/project_dex_archive/debug/out/es/jcyl/ita/frmdrd/render/FormRenderer$2.dex
git rm --cached app/build/intermediates/project_dex_archive/debug/out/es/jcyl/ita/frmdrd/render/FormRenderer$3.dex
git rm --cached app/build/intermediates/project_dex_archive/debug/out/es/jcyl/ita/frmdrd/render/FormRenderer.dex
git rm --cached app/build/intermediates/project_dex_archive/debug/out/es/jcyl/ita/frmdrd/render/ListEntityAdapter$1.dex
git rm --cached app/build/intermediates/project_dex_archive/debug/out/es/jcyl/ita/frmdrd/render/ListEntityAdapter$ViewHolder.dex
git rm --cached app/build/intermediates/project_dex_archive/debug/out/es/jcyl/ita/frmdrd/render/ListEntityAdapter.dex
git rm --cached app/build/intermediates/project_dex_archive/debug/out/es/jcyl/ita/frmdrd/render/ListEntityDialog$1.dex
git rm --cached app/build/intermediates/project_dex_archive/debug/out/es/jcyl/ita/frmdrd/render/ListEntityDialog.dex
git rm --cached app/build/intermediates/project_dex_archive/debug/out/es/jcyl/ita/frmdrd/render/OnChangeFieldInterceptor.dex
git rm --cached app/build/intermediates/project_dex_archive/debug/out/es/jcyl/ita/frmdrd/render/RendererFactory.dex
git rm --cached app/build/intermediates/project_dex_archive/debug/out/es/jcyl/ita/frmdrd/render/TableFieldRenderer$1.dex
git rm --cached app/build/intermediates/project_dex_archive/debug/out/es/jcyl/ita/frmdrd/render/TableFieldRenderer.dex
git rm --cached app/build/intermediates/project_dex_archive/debug/out/es/jcyl/ita/frmdrd/render/TextFieldRenderer$1.dex
git rm --cached app/build/intermediates/project_dex_archive/debug/out/es/jcyl/ita/frmdrd/render/TextFieldRenderer.dex
git rm --cached app/build/intermediates/project_dex_archive/debug/out/es/jcyl/ita/frmdrd/render/UIFieldRenderer.dex
git rm --cached app/build/intermediates/project_dex_archive/debug/out/es/jcyl/ita/frmdrd/ui/form/UIComponent.dex
git rm --cached app/build/intermediates/project_dex_archive/debug/out/es/jcyl/ita/frmdrd/ui/form/UIField$TYPE.dex
git rm --cached app/build/intermediates/project_dex_archive/debug/out/es/jcyl/ita/frmdrd/ui/form/UIField.dex
git rm --cached app/build/intermediates/project_dex_archive/debug/out/es/jcyl/ita/frmdrd/ui/form/UIForm.dex
git rm --cached app/build/intermediates/project_dex_archive/debug/out/es/jcyl/ita/frmdrd/ui/form/UITab.dex
git rm --cached app/build/intermediates/project_dex_archive/debug/out/es/jcyl/ita/frmdrd/util/DataUtils.dex
git rm --cached app/build/intermediates/res/merged/debug/drawable-hdpi_ic_action_new.png.flat
git rm --cached app/build/intermediates/res/merged/debug/drawable-hdpi_ic_action_next_item.png.flat
git rm --cached app/build/intermediates/res/merged/debug/drawable-hdpi_ic_action_previous_item.png.flat
git rm --cached app/build/intermediates/res/merged/debug/drawable-hdpi_ic_launcher.png.flat
git rm --cached app/build/intermediates/res/merged/debug/drawable-hdpi_ic_tool_x.png.flat
git rm --cached app/build/intermediates/res/merged/debug/drawable-mdpi_ic_launcher.png.flat
git rm --cached app/build/intermediates/res/merged/debug/drawable-xhdpi_ic_launcher.png.flat
git rm --cached app/build/intermediates/res/merged/debug/drawable-xxhdpi_ic_launcher.png.flat
git rm --cached app/build/intermediates/res/merged/debug/drawable_selectablebuttonbackground.xml.flat
git rm --cached app/build/intermediates/res/merged/debug/layout_activity_main.xml.flat
git rm --cached app/build/intermediates/res/merged/debug/layout_content_main.xml.flat
git rm --cached app/build/intermediates/res/merged/debug/layout_form_list.xml.flat
git rm --cached app/build/intermediates/res/merged/debug/layout_fragment_item.xml.flat
git rm --cached app/build/intermediates/res/merged/debug/layout_list_field_layout.xml.flat
git rm --cached app/build/intermediates/res/merged/debug/layout_list_item.xml.flat
git rm --cached app/build/intermediates/res/merged/debug/layout_list_item_header.xml.flat
git rm --cached app/build/intermediates/res/merged/debug/layout_list_item_textview.xml.flat
git rm --cached app/build/intermediates/res/merged/debug/layout_tool_alphaedit_boolean.xml.flat
git rm --cached app/build/intermediates/res/merged/debug/layout_tool_alphaedit_date.xml.flat
git rm --cached app/build/intermediates/res/merged/debug/layout_tool_alphaedit_finisher_fromxml.xml.flat
git rm --cached app/build/intermediates/res/merged/debug/layout_tool_alphaedit_text.xml.flat
git rm --cached app/build/intermediates/res/merged/debug/menu_bottom_nav_menu.xml.flat
git rm --cached app/build/intermediates/res/merged/debug/menu_menu_main.xml.flat
git rm --cached app/build/intermediates/res/merged/debug/values-af_values-af.arsc.flat
git rm --cached app/build/intermediates/res/merged/debug/values-am_values-am.arsc.flat
git rm --cached app/build/intermediates/res/merged/debug/values-ar_values-ar.arsc.flat
git rm --cached app/build/intermediates/res/merged/debug/values-as_values-as.arsc.flat
git rm --cached app/build/intermediates/res/merged/debug/values-az_values-az.arsc.flat
git rm --cached app/build/intermediates/res/merged/debug/values-b+sr+Latn_values-b+sr+Latn.arsc.flat
git rm --cached app/build/intermediates/res/merged/debug/values-be_values-be.arsc.flat
git rm --cached app/build/intermediates/res/merged/debug/values-bg_values-bg.arsc.flat
git rm --cached app/build/intermediates/res/merged/debug/values-bn_values-bn.arsc.flat
git rm --cached app/build/intermediates/res/merged/debug/values-bs_values-bs.arsc.flat
git rm --cached app/build/intermediates/res/merged/debug/values-ca_values-ca.arsc.flat
git rm --cached app/build/intermediates/res/merged/debug/values-cs_values-cs.arsc.flat
git rm --cached app/build/intermediates/res/merged/debug/values-da_values-da.arsc.flat
git rm --cached app/build/intermediates/res/merged/debug/values-de_values-de.arsc.flat
git rm --cached app/build/intermediates/res/merged/debug/values-el_values-el.arsc.flat
git rm --cached app/build/intermediates/res/merged/debug/values-en-rAU_values-en-rAU.arsc.flat
git rm --cached app/build/intermediates/res/merged/debug/values-en-rCA_values-en-rCA.arsc.flat
git rm --cached app/build/intermediates/res/merged/debug/values-en-rGB_values-en-rGB.arsc.flat
git rm --cached app/build/intermediates/res/merged/debug/values-en-rIN_values-en-rIN.arsc.flat
git rm --cached app/build/intermediates/res/merged/debug/values-en-rXC_values-en-rXC.arsc.flat
git rm --cached app/build/intermediates/res/merged/debug/values-es-rUS_values-es-rUS.arsc.flat
git rm --cached app/build/intermediates/res/merged/debug/values-es_values-es.arsc.flat
git rm --cached app/build/intermediates/res/merged/debug/values-et_values-et.arsc.flat
git rm --cached app/build/intermediates/res/merged/debug/values-eu_values-eu.arsc.flat
git rm --cached app/build/intermediates/res/merged/debug/values-fa_values-fa.arsc.flat
git rm --cached app/build/intermediates/res/merged/debug/values-fi_values-fi.arsc.flat
git rm --cached app/build/intermediates/res/merged/debug/values-fr-rCA_values-fr-rCA.arsc.flat
git rm --cached app/build/intermediates/res/merged/debug/values-fr_values-fr.arsc.flat
git rm --cached app/build/intermediates/res/merged/debug/values-gl_values-gl.arsc.flat
git rm --cached app/build/intermediates/res/merged/debug/values-gu_values-gu.arsc.flat
git rm --cached app/build/intermediates/res/merged/debug/values-h720dp-v13_values-h720dp-v13.arsc.flat
git rm --cached app/build/intermediates/res/merged/debug/values-hdpi-v4_values-hdpi-v4.arsc.flat
git rm --cached app/build/intermediates/res/merged/debug/values-hi_values-hi.arsc.flat
git rm --cached app/build/intermediates/res/merged/debug/values-hr_values-hr.arsc.flat
git rm --cached app/build/intermediates/res/merged/debug/values-hu_values-hu.arsc.flat
git rm --cached app/build/intermediates/res/merged/debug/values-hy_values-hy.arsc.flat
git rm --cached app/build/intermediates/res/merged/debug/values-in_values-in.arsc.flat
git rm --cached app/build/intermediates/res/merged/debug/values-is_values-is.arsc.flat
git rm --cached app/build/intermediates/res/merged/debug/values-it_values-it.arsc.flat
git rm --cached app/build/intermediates/res/merged/debug/values-iw_values-iw.arsc.flat
git rm --cached app/build/intermediates/res/merged/debug/values-ja_values-ja.arsc.flat
git rm --cached app/build/intermediates/res/merged/debug/values-ka_values-ka.arsc.flat
git rm --cached app/build/intermediates/res/merged/debug/values-kk_values-kk.arsc.flat
git rm --cached app/build/intermediates/res/merged/debug/values-km_values-km.arsc.flat
git rm --cached app/build/intermediates/res/merged/debug/values-kn_values-kn.arsc.flat
git rm --cached app/build/intermediates/res/merged/debug/values-ko_values-ko.arsc.flat
git rm --cached app/build/intermediates/res/merged/debug/values-ky_values-ky.arsc.flat
git rm --cached app/build/intermediates/res/merged/debug/values-land_values-land.arsc.flat
git rm --cached app/build/intermediates/res/merged/debug/values-large-v4_values-large-v4.arsc.flat
git rm --cached app/build/intermediates/res/merged/debug/values-ldltr-v21_values-ldltr-v21.arsc.flat
git rm --cached app/build/intermediates/res/merged/debug/values-lo_values-lo.arsc.flat
git rm --cached app/build/intermediates/res/merged/debug/values-lt_values-lt.arsc.flat
git rm --cached app/build/intermediates/res/merged/debug/values-lv_values-lv.arsc.flat
git rm --cached app/build/intermediates/res/merged/debug/values-mk_values-mk.arsc.flat
git rm --cached app/build/intermediates/res/merged/debug/values-ml_values-ml.arsc.flat
git rm --cached app/build/intermediates/res/merged/debug/values-mn_values-mn.arsc.flat
git rm --cached app/build/intermediates/res/merged/debug/values-mr_values-mr.arsc.flat
git rm --cached app/build/intermediates/res/merged/debug/values-ms_values-ms.arsc.flat
git rm --cached app/build/intermediates/res/merged/debug/values-my_values-my.arsc.flat
git rm --cached app/build/intermediates/res/merged/debug/values-nb_values-nb.arsc.flat
git rm --cached app/build/intermediates/res/merged/debug/values-ne_values-ne.arsc.flat
git rm --cached app/build/intermediates/res/merged/debug/values-night-v8_values-night-v8.arsc.flat
git rm --cached app/build/intermediates/res/merged/debug/values-nl_values-nl.arsc.flat
git rm --cached app/build/intermediates/res/merged/debug/values-or_values-or.arsc.flat
git rm --cached app/build/intermediates/res/merged/debug/values-pa_values-pa.arsc.flat
git rm --cached app/build/intermediates/res/merged/debug/values-pl_values-pl.arsc.flat
git rm --cached app/build/intermediates/res/merged/debug/values-port_values-port.arsc.flat
git rm --cached app/build/intermediates/res/merged/debug/values-pt-rBR_values-pt-rBR.arsc.flat
git rm --cached app/build/intermediates/res/merged/debug/values-pt-rPT_values-pt-rPT.arsc.flat
git rm --cached app/build/intermediates/res/merged/debug/values-pt_values-pt.arsc.flat
git rm --cached app/build/intermediates/res/merged/debug/values-ro_values-ro.arsc.flat
git rm --cached app/build/intermediates/res/merged/debug/values-ru_values-ru.arsc.flat
git rm --cached app/build/intermediates/res/merged/debug/values-si_values-si.arsc.flat
git rm --cached app/build/intermediates/res/merged/debug/values-sk_values-sk.arsc.flat
git rm --cached app/build/intermediates/res/merged/debug/values-sl_values-sl.arsc.flat
git rm --cached app/build/intermediates/res/merged/debug/values-sq_values-sq.arsc.flat
git rm --cached app/build/intermediates/res/merged/debug/values-sr_values-sr.arsc.flat
git rm --cached app/build/intermediates/res/merged/debug/values-sv_values-sv.arsc.flat
git rm --cached app/build/intermediates/res/merged/debug/values-sw600dp-v13_values-sw600dp-v13.arsc.flat
git rm --cached app/build/intermediates/res/merged/debug/values-sw_values-sw.arsc.flat
git rm --cached app/build/intermediates/res/merged/debug/values-ta_values-ta.arsc.flat
git rm --cached app/build/intermediates/res/merged/debug/values-te_values-te.arsc.flat
git rm --cached app/build/intermediates/res/merged/debug/values-th_values-th.arsc.flat
git rm --cached app/build/intermediates/res/merged/debug/values-tl_values-tl.arsc.flat
git rm --cached app/build/intermediates/res/merged/debug/values-tr_values-tr.arsc.flat
git rm --cached app/build/intermediates/res/merged/debug/values-uk_values-uk.arsc.flat
git rm --cached app/build/intermediates/res/merged/debug/values-ur_values-ur.arsc.flat
git rm --cached app/build/intermediates/res/merged/debug/values-uz_values-uz.arsc.flat
git rm --cached app/build/intermediates/res/merged/debug/values-v16_values-v16.arsc.flat
git rm --cached app/build/intermediates/res/merged/debug/values-v17_values-v17.arsc.flat
git rm --cached app/build/intermediates/res/merged/debug/values-v18_values-v18.arsc.flat
git rm --cached app/build/intermediates/res/merged/debug/values-v21_values-v21.arsc.flat
git rm --cached app/build/intermediates/res/merged/debug/values-v22_values-v22.arsc.flat
git rm --cached app/build/intermediates/res/merged/debug/values-v23_values-v23.arsc.flat
git rm --cached app/build/intermediates/res/merged/debug/values-v24_values-v24.arsc.flat
git rm --cached app/build/intermediates/res/merged/debug/values-v25_values-v25.arsc.flat
git rm --cached app/build/intermediates/res/merged/debug/values-v26_values-v26.arsc.flat
git rm --cached app/build/intermediates/res/merged/debug/values-v28_values-v28.arsc.flat
git rm --cached app/build/intermediates/res/merged/debug/values-vi_values-vi.arsc.flat
git rm --cached app/build/intermediates/res/merged/debug/values-watch-v20_values-watch-v20.arsc.flat
git rm --cached app/build/intermediates/res/merged/debug/values-watch-v21_values-watch-v21.arsc.flat
git rm --cached app/build/intermediates/res/merged/debug/values-xlarge-v4_values-xlarge-v4.arsc.flat
git rm --cached app/build/intermediates/res/merged/debug/values-zh-rCN_values-zh-rCN.arsc.flat
git rm --cached app/build/intermediates/res/merged/debug/values-zh-rHK_values-zh-rHK.arsc.flat
git rm --cached app/build/intermediates/res/merged/debug/values-zh-rTW_values-zh-rTW.arsc.flat
git rm --cached app/build/intermediates/res/merged/debug/values-zu_values-zu.arsc.flat
git rm --cached app/build/intermediates/res/merged/debug/values_values.arsc.flat
git rm --cached app/build/intermediates/runtime_symbol_list/debug/R.txt
git rm --cached app/build/intermediates/symbol_list_with_package_name/debug/package-aware-r.txt
git rm --cached app/build/outputs/apk/debug/app-debug.apk
git rm --cached app/build/outputs/logs/manifest-merger-debug-report.txt
git rm --cached local.properties